{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This project is based on the MAGIC Gamma Telescope Data Set from the UCI Machine Learning Repository. The data set contains 19020 gamma-ray observations and 12332 hadron observations. The goal is to classify the observations as either gamma-ray or hadron. The data set contains 11 features, which are described below. The data set is available at https://archive.ics.uci.edu/ml/datasets/MAGIC+Gamma+Telescope. It follows along with the \"Machine Learning for Everyone\" video from FreeCodeCamp.org. The video can be found at https://www.youtube.com/watch?v=7eh4d6sabA0. At certain sections of the project additional sections are added to explain the code and the concepts behind it. Also certain sections might have added code and features which are not in the original video. The original video is a great introduction to ML and is highly recommended. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:52.474 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/a9a21462-6f58-47c0-8ed7-23fe1dee0f40/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from imblearn.over_sampling import RandomOverSampler"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Data Set Information:\n",
    "\n",
    "The data are MC generated (see below) to simulate registration of high energy gamma particles in a ground-based atmospheric Cherenkov gamma telescope using the imaging technique. Cherenkov gamma telescope observes high energy gamma rays, taking advantage of the radiation emitted by charged particles produced inside the electromagnetic showers initiated by the gammas, and developing in the atmosphere. This Cherenkov radiation (of visible to UV wavelengths) leaks through the atmosphere and gets recorded in the detector, allowing reconstruction of the shower parameters. The available information consists of pulses left by the incoming Cherenkov photons on the photomultiplier tubes, arranged in a plane, the camera. Depending on the energy of the primary gamma, a total of few hundreds to some 10000 Cherenkov photons get collected, in patterns (called the shower image), allowing to discriminate statistically those caused by primary gammas (signal) from the images of hadronic showers initiated by cosmic rays in the upper atmosphere (background).\n",
    "\n",
    "Typically, the image of a shower after some pre-processing is an elongated cluster. Its long axis is oriented towards the camera center if the shower axis is parallel to the telescope's optical axis, i.e. if the telescope axis is directed towards a point source. A principal component analysis is performed in the camera plane, which results in a correlation axis and defines an ellipse. If the depositions were distributed as a bivariate Gaussian, this would be an equidensity ellipse. The characteristic parameters of this ellipse (often called Hillas parameters) are among the image parameters that can be used for discrimination. The energy depositions are typically asymmetric along the major axis, and this asymmetry can also be used in discrimination. There are, in addition, further discriminating characteristics, like the extent of the cluster in the image plane, or the total sum of depositions.\n",
    "\n",
    "The data set was generated by a Monte Carlo program, Corsika, described in:\n",
    "D. Heck et al., CORSIKA, A Monte Carlo code to simulate extensive air showers,\n",
    "Forschungszentrum Karlsruhe FZKA 6019 (1998).\n",
    "[Web Link]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "cols=['fLength','fWidth','fSize','fConc','fConc1','fAsym','fM3Long','fM3Trans','fAlpha','fDist','class']\n",
    "df = pd.read_csv(\"magic04.data\", names=cols)\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "df[\"class\"].unique()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We can see we have 2 main types of classes: g(gammas) and g(hadrons). But since computers are better at understanding numbers than letters we will convert these two classes to numbers (0,1) by converting them into integers: "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "df[\"class\"] = df[\"class\"].map({\"g\":1, \"h\":0})"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "If we run the code that gives us the array of our unique classes again we now see that these are now composed of zeros and ones: "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "df[\"class\"].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "What we can do next is, for each data feature (represented in the for loop with \"label\") plot a histogram that will allow us to quickly visualize our data and see if there are any obvious correlations between certain range of values of our features and the particle class. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "for label in cols[:-1]:\n",
    "    plt.hist(df[df[\"class\"]==1][label], alpha=0.7, label=\"gamma\", density=True)\n",
    "    plt.hist(df[df[\"class\"]==0][label], alpha=0.7, label=\"hadron\", density=True)\n",
    "    plt.title(label)\n",
    "    plt.ylabel(\"Probability\")\n",
    "    plt.legend()\n",
    "    plt.show()\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Next we are going to build our train, validation and test sets. We will use 60% of our data for training, 20% for validation and 20% for testing."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "train, valid, test = np.split(df.sample(frac=1), [int(.6*len(df)), int(.8*len(df))])"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "If we look at the different scales of our features we can see that they are not all on the same scale. This can be problematic for our model since it will be difficult for it to learn the weights of the different features. \n",
    "\n",
    "Optimization algorithms are used to train machine learning models by finding the set of weights that minimize the error of the model on the training data. These algorithms use mathematical techniques to iteratively adjust the weights in order to minimize the error.\n",
    "\n",
    "Optimization algorithms are sensitive to the scale of the features because the error function used to evaluate the model's performance is often based on the difference between the predicted values and the true values. If the scales of the features are significantly different, then the error function may be dominated by the features with larger scales, even if those features are not as important for predicting the target variable. Since higher scale features will have larger absolute differences between the predicted values and the true values. \n",
    "\n",
    "For example, consider a model that is trying to predict the price of a house based on the size of the house (measured in square feet) and the number of bedrooms. If the size of the house is measured in the thousands of square feet, but the number of bedrooms is only measured in the single digits, then the scale of the \"size\" feature will be much larger than the scale of the \"bedrooms\" feature. As a result, the error function may be dominated by the \"size\" feature, even if the \"bedrooms\" feature is actually more important for predicting the price of the house.\n",
    "\n",
    "This can lead to suboptimal model performance, because the model is weighting the features incorrectly. In order to address this issue, it is often helpful to scale the features so that they are on a similar scale before training the model. This can be done using techniques such as min-max scaling or standardization. Scaling the features can help the model to more accurately estimate the relative importance of the different features, which can improve model performance.\n",
    "\n",
    "To do this from sklearn.preprocessing we import StandardScaler and then we create a scaler object, and then we fit the scaler to our data. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "def scale_dataset(dataframe, oversample=False):\n",
    "    x = dataframe[dataframe.columns[:-1]].values\n",
    "    y = dataframe[dataframe.columns[-1]].values\n",
    "\n",
    "    scaler = StandardScaler()\n",
    "    x = scaler.fit_transform(x)\n",
    "\n",
    "    if oversample:\n",
    "        ros = RandomOverSampler()\n",
    "        x, y = ros.fit_resample(x, y)\n",
    "\n",
    "    data = np.hstack((x, np.reshape(y, (-1,1))))\n",
    "    return data, x, y"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We should now look at how many occurrences of each class we have in our training set. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "print(len(train[train[\"class\"]==1])) #gamma\n",
    "print(len(train[train[\"class\"]==0])) #hadron"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Since there is a big difference in the number of occurrences of each class we should consider using oversampling as to not bias our model towards the class with the most occurrences. To to this we added the oversampling parameter to our scaler_dataset function (above).\n",
    "\n",
    "What the oversample function does is it takes the minority class (hadrons) and randomly duplicates it until it has the same number of occurrences as the majority class (gammas).\n",
    "\n",
    "By default we put the oversample to False. But when we call the train we will set it to True. Hence the \"if oversample:\" statement."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "#train, x_train, y_train = scale_dataset(train, oversample=True)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Let's double check the number of occurrences of each class in our training set after oversampling."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "#print(len(y_train))\n",
    "#print(sum(y_train == 1)) #gamma\n",
    "#print(sum(y_train == 0)) #hadron\n",
    "\n",
    "#these commands were used only to verify that the oversampling worked, that is why they are commented out and I just left the output below. "
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Total Number of Classifications: 14756;\n",
    "Total Occurrences in Class 1: 7378;\n",
    "Total Occurrences in Class 0: 7378;\n",
    "\n",
    "Indeed we see that the number of occurrences of each class is now the same and we can have confidence that our model will not be biased towards a class. "
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Below the oversample parameter is set to True for the first call to scale_dataset to apply oversampling to the training data, and set to False for the last two calls to avoid oversampling the validation and test data. This is done to ensure that the validation and test sets are representative of the true distribution of the data, and to avoid artificially inflating the performance of the model on those sets."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "\n",
    "train, x_train, y_train = scale_dataset(train, oversample=True)\n",
    "valid, x_valid, y_valid = scale_dataset(valid, oversample=False)\n",
    "test, x_test, y_test = scale_dataset(test, oversample=False)\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now that we have our data ready we will go through several different ML models and apply them to our data. We will go through KNN, Naive Bayes, Logistic Regression, SVM, Neural Networks (NN), Classification NN using Tensor Flow, Linear Regression, Linear Regression NN using Tensor Flow, K-means Clustering, and finally Principal Component Analysis (PCA). But first let's start with a simple model: KNN:"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "KNN: K-Nearest Neighbors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.metrics import classification_report"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Next we will use the KNN algorithm to classify our data and see how well it performs by printing out the classification report. We can try out different amounts of neighbors and see how the accuracy changes. But after a few manual iterations I see we seem to get the best accuracy when we use 13 neighbors. We reached an accuracy of 0.83%. Also keep in mind that more neighbhors means more computation time at diminishing returns. There is not a big difference (relative) in terms of accuracy score between 13 and 5 neighbors (0.01% difference). Note, you should use an odd number of neighbors to avoid ties."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "knn_model = KNeighborsClassifier(n_neighbors=13)\n",
    "knn_model.fit(x_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "y_pred = knn_model.predict(x_test)\n",
    "print(classification_report(y_test, y_pred, target_names=[\"hadron\", \"gamma\"]))"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "But what if there is another K value with a better accuracy score? How can we make an automated way to find the best amount of neighbors? \n",
    "We can use a for loop to iterate through different amounts of neighbors and see which one gives us the best accuracy.\n",
    "And then we represent that iteration in a graph using matplotlib's pyplot."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "k_values = range(1, 50)\n",
    "acc_score = []\n",
    "for i in k_values:\n",
    "    knn_model = KNeighborsClassifier(n_neighbors=i)\n",
    "    knn_model.fit(x_train, y_train)\n",
    "    y_pred = knn_model.predict(x_test)\n",
    "    acc_score.append(knn_model.score(x_test, y_test))\n",
    "\n",
    "optimal_k = k_values[acc_score.index(max(acc_score))]\n",
    "\n",
    "plt.plot(k_values, acc_score, color='blue',linestyle='dashed', marker='o')\n",
    "plt.figsize = (10, 6)\n",
    "plt.xlabel(\"K\")\n",
    "plt.ylabel(\"Accuracy\")\n",
    "plt.title(\"KNN Accuracy\")\n",
    "plt.suptitle(f\"The optimal value of K is {optimal_k} with an accuracy of {max(acc_score):.2f}%.\", y=1.05)\n",
    "plt.axvline(optimal_k, color='green', linewidth=2)\n",
    "plt.annotate(f\"{optimal_k}\", xy=(optimal_k, max(acc_score)), xytext=(optimal_k + 0.5, max(acc_score)))\n",
    "plt.show()\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now that we have our best K value we can use it to train our model and then print out the classification report."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "knn_model = KNeighborsClassifier(n_neighbors=optimal_k)\n",
    "knn_model.fit(x_train, y_train)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "y_pred = knn_model.predict(x_test)\n",
    "print(classification_report(y_test, y_pred, target_names=[\"hadron\", \"gamma\"]))\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Let's dissect the classification report: \n",
    "- The first column is the precision of the model. Precision is the number of true positives divided by the number of true positives plus the number of false positives. The higher the precision score the lowest the number of false positives. In other terms, how many of the ones(zeros) we labeled as ones(zeros) were actually ones(zeros).\n",
    "- The second column is the recall of the model. Recall is the number of true positives divided by the number of true positives plus the number of false negatives. The higher the recall score the lowest the number of false negatives. In simpler terms, how many of the ones(zeros) did we label as ones(zeros).\n",
    "- The third column is the f1-score of the model. The f1-score is the harmonic mean of the precision and recall. The higher the f1-score the better the model.\n",
    "- The fourth column is the support of the model. Support is the number of occurrences of each class in the test set.\n",
    "- The accuracy of the model is the average of the precision, recall, and f1-score for each class.\n",
    "- The macro average is the average of the metric computed for each class\n",
    "- The weighted average is the average of the metric, weighted by the number of true instances for each class.\n",
    "- The support is the number of occurrences of each class in the test set.\n",
    "\n",
    "\n",
    "For example, consider a classification report with two classes, A and B. The precision, recall, and f1-score for class A are 0.8, 0.7, and 0.75, respectively, and the precision, recall, and f1-score for class B are 0.6, 0.9, and 0.72, respectively. In this case, the macro average for precision would be (0.8 + 0.6) / 2 = 0.7, the macro average for recall would be (0.7 + 0.9) / 2 = 0.8, and the macro average for f1-score would be (0.75 + 0.72) / 2 = 0.735.\n",
    "\n",
    "On the other hand, if class A has 10 true instances and class B has 5 true instances, the weighted average for precision would be (0.8 * 10 + 0.6 * 5) / 15 = 0.76, the weighted average for recall would be (0.7 * 10 + 0.9 * 5) / 15 = 0.78, and the weighted average for f1-score would be (0.75 * 10 + 0.72 * 5) / 15 = 0.737.\n",
    "\n",
    "The choice between using the macro average or the weighted average in a classification report depends on the specific context and the goals of the evaluation. The macro average is useful when you want to balance the metric across all classes, while the weighted average is useful when you want to give more weight to classes with more instances."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "And that's a wrap for KNN. Let's move on to Naive Bayes:"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Naive Bayes\n",
    "\n",
    "[label](../../../../Desktop/Screenshot%202022-12-26%20at%2015.29.43.png%0D) ![Alt text](../../../../Desktop/Screenshot%202022-12-26%20at%2015.29.54.png)\n",
    "\n",
    "To understand Naive Bayes we need to understand Bayes Theorem. Bayes Theorem is a way to calculate the probability of an event based on prior knowledge of conditions that might be related to the event. Bayes Theorem is stated mathematically as the following equation:\n",
    "P(A|B) = P(B|A) * P(A) / P(B)\n",
    "\n",
    "Where P(A|B) is a conditional probability: the likelihood of event A occurring given that B is true. P(B|A) is also a conditional probability: the likelihood of event B occurring given that A is true. P(A) and P(B) are the probabilities of observing A and B respectively.\n",
    "\n",
    "I recommend you see this video by Krish Naik (a great tutor of Data Science btw) to have a better understanding of Bayes Theorem: https://www.youtube.com/watch?v=jS1CKhALUBQ&ab_channel=KrishNaik"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The code to implement this algorithm is very simple. We just need to call the GaussianNB function from the sklearn library and then call the fit function to train our model. Then we can print out the classification report."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "from sklearn.naive_bayes import GaussianNB\n",
    "nb_model = GaussianNB()\n",
    "nb_model = nb_model.fit(x_train, y_train)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 824, in parse_command_line\n",
      "\u001b[1;31m    self.update_config(self.cli_config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 230, in update_config\n",
      "\u001b[1;31m    self._load_config(config)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/configurable.py\", line 167, in _load_config\n",
      "\u001b[1;31m    with self.hold_trait_notifications():\n",
      "\u001b[1;31m  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py\", line 144, in __exit__\n",
      "\u001b[1;31m    next(self.gen)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1362, in hold_trait_notifications\n",
      "\u001b[1;31m    raise e\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1348, in hold_trait_notifications\n",
      "\u001b[1;31m    value = trait._cross_validate(self, getattr(self, name))\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 729, in _cross_validate\n",
      "\u001b[1;31m    value = obj._trait_validators<a href='obj, proposal'>self.name</a>\n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/traitlets.py\", line 1132, in __call__\n",
      "\u001b[1;31m    return self.func(*args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1523, in _notebook_dir_validate\n",
      "\u001b[1;31m    raise TraitError(trans.gettext(\"No such notebook dir: '%r'\") % value)\n",
      "\u001b[1;31mtraitlets.traitlets.TraitError: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "\u001b[1;31m    return func(self, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 111, in m_exec_module_observable\n",
      "\u001b[1;31m    self._start_notebook(args, cwd, env)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 168, in _start_notebook\n",
      "\u001b[1;31m    app.launch_new_instance()\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 276, in launch_instance\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 981, in launch_instance\n",
      "\u001b[1;31m    app.initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 2142, in initialize\n",
      "\u001b[1;31m    super().initialize(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 110, in inner\n",
      "\u001b[1;31m    return method(app, *args, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/jupyter_core/application.py\", line 247, in initialize\n",
      "\u001b[1;31m    self.parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/notebook/notebookapp.py\", line 1612, in parse_command_line\n",
      "\u001b[1;31m    super().parse_command_line(argv)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 114, in inner\n",
      "\u001b[1;31m    app.exit(1)\n",
      "\u001b[1;31m  File \"/Users/andrerodriguespereira/Library/Python/3.11/lib/python/site-packages/traitlets/config/application.py\", line 969, in exit\n",
      "\u001b[1;31m    sys.exit(exit_status)\n",
      "\u001b[1;31mSystemExit: 1\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[C 20:32:45.415 NotebookApp] Bad config encountered during initialization: No such notebook dir: ''/Colonizer/ML_Beguinner_Projects''\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mFailed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/Colonizer/ML_Beguinner_Projects\" --config=/var/folders/j0/8nhddq_55kg673c8fwq4v25m0000gn/T/4c46fb8d-4b47-4f2b-ae85-80e26ad17f50/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0"
     ]
    }
   ],
   "source": [
    "y_pred = nb_model.predict(x_test)\n",
    "print(classification_report(y_test, y_pred, target_names=[\"hadron\", \"gamma\"]))"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "As you can see our accuracy score is lower than the classification report we got from KNN. Let's move on to Logistic Regression:"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Logistic Regression"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
